name: kinopoisk_bloc_four
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  google_fonts: ^5.1.0
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  stream_transform: ^2.1.0

  search_movies_repository:
    path: packages/search_mvoies_repository
  movie_awards_repository:
    path: packages/movie_awards_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true