name: movie_details_repository
description: packages/movie_details_repository
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true